name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build and release
    strategy:
      matrix:
        include:
          # Windows 64-bit
          - os: windows-latest
            target: x86_64-pc-windows-msvc

          # Linux 64-bit
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin

          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: chnroutes
          target: ${{ matrix.target }}
          features: bin
          tar: unix
          zip: windows
          include: LICENSE,README.md
