matrix:
  include:
    - os: ubuntu-latest
      target: x86_64-unknown-linux-gnu
      asset_name: chnroutes-rs-next-x86_64-unknown-linux-gnu.tar.gz

    - os: windows-latest
      target: x86_64-pc-windows-msvc
      asset_name: chnroutes-rs-next-x86_64-pc-windows-msvc.zip

    - os: macos-latest
      target: aarch64-apple-darwin
      asset_name: chnroutes-rs-next-aarch64-apple-darwin.tar.gz